// Send to AEForm.jsx for local origin table
export const LocalRegions = [
    {
        id: 0,
        name: "National Capital Local - NCR",
    },
    {
        id: 1,
        name: "Cordillera Administrative Local - CAR",
    },
    {
        id: 2,
        name: "Local I - Ilocos Local",
    },
    {
        id: 3,
        name: "Local II - Cagayan Valley",
    },
    {
        id: 4,
        name: "Local III - Central Luzon",
    },
    {
        id: 5,
        name: "Local IVA - CALABARZON",
    },
    {
        id: 6,
        name: "Local IVB - MIMAROPA",
    },
    {
        id: 7,
        name: "Local V - Bicol Local",
    },
    {
        id: 8,
        name: "Local VI - Western Visayas",
    },
    {
        id: 9,
        name: "Local VII - Central Visayas",
    },
    {
        id: 10,
        name: "Local VIII - Eastern Visayas",
    },
    {
        id: 11,
        name: "Local IX - Zamboanga Peninsula",
    },
    {
        id: 12,
        name: "Local X - Northern Mindanao",
    },
    {
        id: 13,
        name: "Local XI - Davao Local",
    },
    {
        id: 14,
        name: "Local XII - SOCCSKSARGEN",
    },
    {
        id: 15,
        name: "Local XIII - Caraga",
    },
    {
        id: 16,
        name: "Bangsamoro Autonomous Local in Muslim Mindanao - BARMM",
    },
    {
        id: 17,
        name: "Unidentified",
    },
];

//Exported to guimarasMapScatter.jsx
export const LocalCoords = [
    {
        region: "NCR",
        island: "Luzon",
        coorLat: 14.594003,
        coorLng: 120.983507,
    },
    {
        region: "CAR",
        island: "Luzon",
        coorLat: 17.254913,
        coorLng: 121.126626,
    },
    {
        region: "Region I",
        island: "Luzon",
        coorLat: 18.1977,
        coorLng: 120.5931,
    },
    {
        region: "Region II",
        island: "Luzon",
        coorLat: 17.090103,
        coorLng: 122.11465,
    },
    {
        region: "Region III",
        island: "Luzon",
        coorLat: 15.367267,
        coorLng: 120.643843,
    },
    {
        region: "Region IV-A",
        island: "Luzon",
        coorLat: 13.878059,
        coorLng: 121.282809,
    },
    {
        region: "Region IV-B",
        island: "Luzon",
        coorLat: 10.264933,
        coorLng: 119.100295,
    },
    {
        region: "Region V",
        island: "Luzon",
        coorLat: 12.9707,
        coorLng: 123.997,
    },
    {
        region: "Region VI",
        island: "Visayas",
        coorLat: 11.0055,
        coorLng: 122.5375,
    },
    {
        region: "Region VII",
        island: "Visayas",
        coorLat: 10.011639,
        coorLng: 123.068412,
    },
    {
        region: "Region VIII",
        island: "Visayas",
        coorLat: 11.2455,
        coorLng: 125.0045,
    },
    {
        region: "Region IX",
        island: "Mindanao",
        coorLat: 7.837629,
        coorLng: 122.426231,
    },
    {
        region: "Region X",
        island: "Mindanao",
        coorLat: 8.456403,
        coorLng: 124.620946,
    },
    {
        region: "Region XI",
        island: "Mindanao",
        coorLat: 7.020016,
        coorLng: 125.670897,
    },
    {
        region: "Region XII",
        island: "Mindanao",
        coorLat: 6.194242,
        coorLng: 124.437052,
    },
    {
        region: "Region XIII",
        island: "Mindanao",
        coorLat: 8.841912,
        coorLng: 126.05756,
    },
    {
        region: "BARMM",
        island: "Mindanao",
        coorLat: 5.813796,
        coorLng: 121.057148,
    },
];

//Exported to guimarasMapScatter.jsx
export const ForeignCoords = [
    {
        region: "Northern Africa",
        continent: "Africa",
        coorLat: 26.765636,
        coorLng: 12.762118,
    },
    {
        region: "Eastern Africa",
        continent: "Africa",
        coorLat: -2.041376,
        coorLng: 39.852019,
    },
    {
        region: "Middle Africa",
        continent: "Africa",
        coorLat: 6.976514,
        coorLng: 17.742377,
    },
    {
        region: "Southern Africa",
        continent: "Africa",
        coorLat: -20.292075,
        coorLng: 23.116197,
    },
    {
        region: "Western Africa",
        continent: "Africa",
        coorLat: 5.482222,
        coorLng: 7.725902,
    },
    {
        region: "Caribbean",
        continent: "North America",
        coorLat: 20.885079,
        coorLng: -73.65898,
    },
    {
        region: "Central America",
        continent: "North America",
        coorLat: 14.606603,
        coorLng: -88.981404,
    },
    {
        region: "South America",
        continent: "South America",
        coorLat: -9.229735,
        coorLng: -55.547721,
    },
    {
        region: "Northern America",
        continent: "North America",
        coorLat: 53.853262,
        coorLng: -105.549629,
    },
    {
        region: "Central Asia",
        continent: "Asia",
        coorLat: 40.223204,
        coorLng: 72.542639,
    },
    {
        region: "Eastern Asia",
        continent: "Asia",
        coorLat: 33.577045,
        coorLng: 120.341193,
    },
    {
        region: "South-eastern Asia",
        continent: "Asia",
        coorLat: 8.011158,
        coorLng: 112.882666,
    },
    {
        region: "Southern Asia",
        continent: "Asia",
        coorLat: 22.920492,
        coorLng: 84.547264,
    },
    {
        region: "Western Asia",
        continent: "Asia",
        coorLat: 34.475345,
        coorLng: 46.506421,
    },
    {
        region: "Eastern Europe",
        continent: "Asia",
        coorLat: 52.0055,
        coorLng: 37.9587,
    },
    {
        region: "Northern Europe",
        continent: "Europe",
        coorLat: 54.449282,
        coorLng: 11.43671,
    },
    {
        region: "Southern Europe",
        continent: "Europe",
        coorLat: 39.812943,
        coorLng: 16.977489,
    },
    {
        region: "Western Europe",
        continent: "Europe",
        coorLat: 46.2022,
        coorLng: 1.2644,
    },
    {
        region: "Australia and New Zealand",
        continent: "Australia",
        coorLat: -33.12397,
        coorLng: 156.780471,
    },
    {
        region: "Melanesia",
        continent: "Oceania",
        coorLat: -13.8536152,
        coorLng: 122.4103147,
    },
    {
        region: "Micronesia",
        continent: "Oceania",
        coorLat: 5.1254832,
        coorLng: 139.5339139,
    },
    {
        region: "Polynesia",
        continent: "Oceania",
        coorLat: -8.0505232,
        coorLng: 137.2548017,
    },
];

// Send to AEForm.jsx for age group table
export const AgeGroup = [
    {
        id: 0,
        name: "Children (0 - 12 Years)",
    },
    {
        id: 1,
        name: "Teenagers (13 - 17 Years)",
    },
    {
        id: 2,
        name: "Young Adults (18 - 35 Years)",
    },
    {
        id: 3,
        name: "Adults (36 - 59 Years)",
    },
    {
        id: 4,
        name: "Seniors (60 Above)",
    },
];

// Send to AEForm.jsx for foreign countries table
export const ForeignCountries = [
    {
        id: 0,
        name: "Cyprus",
        cca2: "CY",
        region: "Southern Europe",
    },
    {
        id: 1,
        name: "Eritrea",
        cca2: "ER",
        region: "Eastern Africa",
    },
    {
        id: 2,
        name: "Liberia",
        cca2: "LR",
        region: "Western Africa",
    },
    {
        id: 3,
        name: "Bermuda",
        cca2: "BM",
        region: "North America",
    },
    {
        id: 4,
        name: "Vatican City",
        cca2: "VA",
        region: "Southern Europe",
    },
    {
        id: 5,
        name: "Cook Islands",
        cca2: "CK",
        region: "Polynesia",
    },
    {
        id: 6,
        name: "Somalia",
        cca2: "SO",
        region: "Eastern Africa",
    },
    {
        id: 7,
        name: "Zambia",
        cca2: "ZM",
        region: "Eastern Africa",
    },
    {
        id: 8,
        name: "Venezuela",
        cca2: "VE",
        region: "South America",
    },
    {
        id: 9,
        name: "Turkmenistan",
        cca2: "TM",
        region: "Central Asia",
    },
    {
        id: 10,
        name: "Albania",
        cca2: "AL",
        region: "Southeast Europe",
    },
    {
        id: 11,
        name: "Croatia",
        cca2: "HR",
        region: "Southeast Europe",
    },
    {
        id: 12,
        name: "United Kingdom",
        cca2: "GB",
        region: "Northern Europe",
    },
    {
        id: 13,
        name: "Sudan",
        cca2: "SD",
        region: "Northern Africa",
    },
    {
        id: 14,
        name: "Timor-Leste",
        cca2: "TL",
        region: "South-Eastern Asia",
    },
    {
        id: 15,
        name: "Republic of the Congo",
        cca2: "CG",
        region: "Middle Africa",
    },
    {
        id: 16,
        name: "Azerbaijan",
        cca2: "AZ",
        region: "Western Asia",
    },
    {
        id: 17,
        name: "Kenya",
        cca2: "KE",
        region: "Eastern Africa",
    },
    {
        id: 18,
        name: "American Samoa",
        cca2: "AS",
        region: "Polynesia",
    },
    {
        id: 19,
        name: "Ivory Coast",
        cca2: "CI",
        region: "Western Africa",
    },
    {
        id: 20,
        name: "Senegal",
        cca2: "SN",
        region: "Western Africa",
    },
    {
        id: 21,
        name: "Vietnam",
        cca2: "VN",
        region: "South-Eastern Asia",
    },
    {
        id: 22,
        name: "El Salvador",
        cca2: "SV",
        region: "Central America",
    },
    {
        id: 23,
        name: "Afghanistan",
        cca2: "AF",
        region: "Southern Asia",
    },
    {
        id: 24,
        name: "Saint Martin",
        cca2: "MF",
        region: "Caribbean",
    },
    {
        id: 25,
        name: "Latvia",
        cca2: "LV",
        region: "Northern Europe",
    },
    {
        id: 26,
        name: "Guatemala",
        cca2: "GT",
        region: "Central America",
    },
    {
        id: 27,
        name: "Kuwait",
        cca2: "KW",
        region: "Western Asia",
    },
    {
        id: 28,
        name: "São Tomé and Príncipe",
        cca2: "ST",
        region: "Middle Africa",
    },
    {
        id: 29,
        name: "Kyrgyzstan",
        cca2: "KG",
        region: "Central Asia",
    },
    {
        id: 30,
        name: "Poland",
        cca2: "PL",
        region: "Central Europe",
    },
    {
        id: 31,
        name: "Guam",
        cca2: "GU",
        region: "Micronesia",
    },
    {
        id: 32,
        name: "Ghana",
        cca2: "GH",
        region: "Western Africa",
    },
    {
        id: 33,
        name: "Lithuania",
        cca2: "LT",
        region: "Northern Europe",
    },
    {
        id: 34,
        name: "Armenia",
        cca2: "AM",
        region: "Western Asia",
    },
    {
        id: 35,
        name: "Jersey",
        cca2: "JE",
        region: "Northern Europe",
    },
    {
        id: 36,
        name: "Grenada",
        cca2: "GD",
        region: "Caribbean",
    },
    {
        id: 37,
        name: "Tajikistan",
        cca2: "TJ",
        region: "Central Asia",
    },
    {
        id: 38,
        name: "Ethiopia",
        cca2: "ET",
        region: "Eastern Africa",
    },
    {
        id: 39,
        name: "Western Sahara",
        cca2: "EH",
        region: "Northern Africa",
    },
    {
        id: 40,
        name: "Morocco",
        cca2: "MA",
        region: "Northern Africa",
    },
    {
        id: 41,
        name: "Puerto Rico",
        cca2: "PR",
        region: "Caribbean",
    },
    {
        id: 42,
        name: "Christmas Island",
        cca2: "CX",
        region: "Australia and New Zealand",
    },
    {
        id: 43,
        name: "New Zealand",
        cca2: "NZ",
        region: "Australia and New Zealand",
    },
    {
        id: 44,
        name: "Brunei",
        cca2: "BN",
        region: "South-Eastern Asia",
    },
    {
        id: 45,
        name: "French Guiana",
        cca2: "GF",
        region: "South America",
    },
    {
        id: 46,
        name: "Niue",
        cca2: "NU",
        region: "Polynesia",
    },
    {
        id: 47,
        name: "Romania",
        cca2: "RO",
        region: "Southeast Europe",
    },
    {
        id: 48,
        name: "Svalbard and Jan Mayen",
        cca2: "SJ",
        region: "Northern Europe",
    },
    {
        id: 49,
        name: "Belarus",
        cca2: "BY",
        region: "Eastern Europe",
    },
    {
        id: 50,
        name: "Panama",
        cca2: "PA",
        region: "Central America",
    },
    {
        id: 51,
        name: "Cameroon",
        cca2: "CM",
        region: "Middle Africa",
    },
    {
        id: 52,
        name: "Czechia",
        cca2: "CZ",
        region: "Central Europe",
    },
    {
        id: 53,
        name: "Saint Barthélemy",
        cca2: "BL",
        region: "Caribbean",
    },
    {
        id: 54,
        name: "Greece",
        cca2: "GR",
        region: "Southern Europe",
    },
    {
        id: 55,
        name: "Mali",
        cca2: "ML",
        region: "Western Africa",
    },
    {
        id: 56,
        name: "Martinique",
        cca2: "MQ",
        region: "Caribbean",
    },
    {
        id: 57,
        name: "France",
        cca2: "FR",
        region: "Western Europe",
    },
    {
        id: 58,
        name: "Pakistan",
        cca2: "PK",
        region: "Southern Asia",
    },
    {
        id: 59,
        name: "Peru",
        cca2: "PE",
        region: "South America",
    },
    {
        id: 60,
        name: "Barbados",
        cca2: "BB",
        region: "Caribbean",
    },
    {
        id: 61,
        name: "Greenland",
        cca2: "GL",
        region: "North America",
    },
    {
        id: 62,
        name: "Saint Pierre and Miquelon",
        cca2: "PM",
        region: "North America",
    },
    {
        id: 63,
        name: "Chad",
        cca2: "TD",
        region: "Middle Africa",
    },
    {
        id: 64,
        name: "Hungary",
        cca2: "HU",
        region: "Central Europe",
    },
    {
        id: 65,
        name: "Comoros",
        cca2: "KM",
        region: "Eastern Africa",
    },
    {
        id: 66,
        name: "Bangladesh",
        cca2: "BD",
        region: "Southern Asia",
    },
    {
        id: 67,
        name: "Tokelau",
        cca2: "TK",
        region: "Polynesia",
    },
    {
        id: 68,
        name: "Fiji",
        cca2: "FJ",
        region: "Melanesia",
    },
    {
        id: 69,
        name: "China",
        cca2: "CN",
        region: "Eastern Asia",
    },
    {
        id: 70,
        name: "Colombia",
        cca2: "CO",
        region: "South America",
    },
    {
        id: 71,
        name: "British Virgin Islands",
        cca2: "VG",
        region: "Caribbean",
    },
    {
        id: 72,
        name: "Algeria",
        cca2: "DZ",
        region: "Northern Africa",
    },
    {
        id: 73,
        name: "Maldives",
        cca2: "MV",
        region: "Southern Asia",
    },
    {
        id: 74,
        name: "Malaysia",
        cca2: "MY",
        region: "South-Eastern Asia",
    },
    {
        id: 75,
        name: "Cayman Islands",
        cca2: "KY",
        region: "Caribbean",
    },
    {
        id: 76,
        name: "Spain",
        cca2: "ES",
        region: "Southern Europe",
    },
    {
        id: 77,
        name: "Ireland",
        cca2: "IE",
        region: "Northern Europe",
    },
    {
        id: 78,
        name: "Estonia",
        cca2: "EE",
        region: "Northern Europe",
    },
    {
        id: 79,
        name: "Paraguay",
        cca2: "PY",
        region: "South America",
    },
    {
        id: 80,
        name: "Uruguay",
        cca2: "UY",
        region: "South America",
    },
    {
        id: 81,
        name: "South Africa",
        cca2: "ZA",
        region: "Southern Africa",
    },
    {
        id: 82,
        name: "Saint Lucia",
        cca2: "LC",
        region: "Caribbean",
    },
    {
        id: 83,
        name: "Vanuatu",
        cca2: "VU",
        region: "Melanesia",
    },
    {
        id: 84,
        name: "Finland",
        cca2: "FI",
        region: "Northern Europe",
    },
    {
        id: 85,
        name: "Sweden",
        cca2: "SE",
        region: "Northern Europe",
    },
    {
        id: 86,
        name: "British Indian Ocean Territory",
        cca2: "IO",
        region: "Eastern Africa",
    },
    {
        id: 87,
        name: "Lebanon",
        cca2: "LB",
        region: "Western Asia",
    },
    {
        id: 88,
        name: "United States",
        cca2: "US",
        region: "North America",
    },
    {
        id: 89,
        name: "Chile",
        cca2: "CL",
        region: "South America",
    },
    {
        id: 90,
        name: "Norfolk Island",
        cca2: "NF",
        region: "Australia and New Zealand",
    },
    {
        id: 91,
        name: "Montserrat",
        cca2: "MS",
        region: "Caribbean",
    },
    {
        id: 92,
        name: "Australia",
        cca2: "AU",
        region: "Australia and New Zealand",
    },
    {
        id: 93,
        name: "Belize",
        cca2: "BZ",
        region: "Central America",
    },
    {
        id: 94,
        name: "Guyana",
        cca2: "GY",
        region: "South America",
    },
    {
        id: 95,
        name: "Mongolia",
        cca2: "MN",
        region: "Eastern Asia",
    },
    {
        id: 96,
        name: "Tuvalu",
        cca2: "TV",
        region: "Polynesia",
    },
    {
        id: 97,
        name: "Dominican Republic",
        cca2: "DO",
        region: "Caribbean",
    },
    {
        id: 98,
        name: "Equatorial Guinea",
        cca2: "GQ",
        region: "Middle Africa",
    },
    {
        id: 99,
        name: "Saint Kitts and Nevis",
        cca2: "KN",
        region: "Caribbean",
    },
    {
        id: 100,
        name: "Bolivia",
        cca2: "BO",
        region: "South America",
    },
    {
        id: 101,
        name: "Nepal",
        cca2: "NP",
        region: "Southern Asia",
    },
    {
        id: 102,
        name: "Sri Lanka",
        cca2: "LK",
        region: "Southern Asia",
    },
    {
        id: 103,
        name: "Taiwan",
        cca2: "TW",
        region: "Eastern Asia",
    },
    {
        id: 104,
        name: "Benin",
        cca2: "BJ",
        region: "Western Africa",
    },
    {
        id: 105,
        name: "Bulgaria",
        cca2: "BG",
        region: "Southeast Europe",
    },
    {
        id: 106,
        name: "Moldova",
        cca2: "MD",
        region: "Eastern Europe",
    },
    {
        id: 107,
        name: "Isle of Man",
        cca2: "IM",
        region: "Northern Europe",
    },
    {
        id: 108,
        name: "Bhutan",
        cca2: "BT",
        region: "Southern Asia",
    },
    {
        id: 109,
        name: "Cambodia",
        cca2: "KH",
        region: "South-Eastern Asia",
    },
    {
        id: 110,
        name: "Antigua and Barbuda",
        cca2: "AG",
        region: "Caribbean",
    },
    {
        id: 111,
        name: "Haiti",
        cca2: "HT",
        region: "Caribbean",
    },
    {
        id: 112,
        name: "Cape Verde",
        cca2: "CV",
        region: "Western Africa",
    },
    {
        id: 113,
        name: "Georgia",
        cca2: "GE",
        region: "Western Asia",
    },
    {
        id: 114,
        name: "Burundi",
        cca2: "BI",
        region: "Eastern Africa",
    },
    {
        id: 115,
        name: "Bahamas",
        cca2: "BS",
        region: "Caribbean",
    },
    {
        id: 116,
        name: "Mauritius",
        cca2: "MU",
        region: "Eastern Africa",
    },
    {
        id: 117,
        name: "Libya",
        cca2: "LY",
        region: "Northern Africa",
    },
    {
        id: 118,
        name: "Malawi",
        cca2: "MW",
        region: "Eastern Africa",
    },
    {
        id: 119,
        name: "Mexico",
        cca2: "MX",
        region: "North America",
    },
    {
        id: 120,
        name: "Eswatini",
        cca2: "SZ",
        region: "Southern Africa",
    },
    {
        id: 121,
        name: "Papua New Guinea",
        cca2: "PG",
        region: "Melanesia",
    },
    {
        id: 122,
        name: "Dominica",
        cca2: "DM",
        region: "Caribbean",
    },
    {
        id: 123,
        name: "Liechtenstein",
        cca2: "LI",
        region: "Western Europe",
    },
    {
        id: 124,
        name: "Russia",
        cca2: "RU",
        region: "Eastern Europe",
    },
    {
        id: 125,
        name: "Israel",
        cca2: "IL",
        region: "Western Asia",
    },
    {
        id: 126,
        name: "Singapore",
        cca2: "SG",
        region: "South-Eastern Asia",
    },
    {
        id: 127,
        name: "Uganda",
        cca2: "UG",
        region: "Eastern Africa",
    },
    {
        id: 128,
        name: "Slovakia",
        cca2: "SK",
        region: "Central Europe",
    },
    {
        id: 129,
        name: "Tonga",
        cca2: "TO",
        region: "Polynesia",
    },
    {
        id: 130,
        name: "United Arab Emirates",
        cca2: "AE",
        region: "Western Asia",
    },
    {
        id: 131,
        name: "Mayotte",
        cca2: "YT",
        region: "Eastern Africa",
    },
    {
        id: 132,
        name: "Suriname",
        cca2: "SR",
        region: "South America",
    },
    {
        id: 133,
        name: "Uzbekistan",
        cca2: "UZ",
        region: "Central Asia",
    },
    {
        id: 134,
        name: "Saudi Arabia",
        cca2: "SA",
        region: "Western Asia",
    },
    {
        id: 135,
        name: "Egypt",
        cca2: "EG",
        region: "Northern Africa",
    },
    {
        id: 136,
        name: "Italy",
        cca2: "IT",
        region: "Southern Europe",
    },
    {
        id: 137,
        name: "Madagascar",
        cca2: "MG",
        region: "Eastern Africa",
    },
    {
        id: 138,
        name: "New Caledonia",
        cca2: "NC",
        region: "Melanesia",
    },
    {
        id: 139,
        name: "Canada",
        cca2: "CA",
        region: "North America",
    },
    {
        id: 140,
        name: "United States Virgin Islands",
        cca2: "VI",
        region: "Caribbean",
    },
    {
        id: 141,
        name: "Marshall Islands",
        cca2: "MH",
        region: "Micronesia",
    },
    {
        id: 142,
        name: "Mauritania",
        cca2: "MR",
        region: "Western Africa",
    },
    {
        id: 143,
        name: "Gambia",
        cca2: "GM",
        region: "Western Africa",
    },
    {
        id: 144,
        name: "Trinidad and Tobago",
        cca2: "TT",
        region: "Caribbean",
    },
    {
        id: 145,
        name: "Seychelles",
        cca2: "SC",
        region: "Eastern Africa",
    },
    {
        id: 146,
        name: "Japan",
        cca2: "JP",
        region: "Eastern Asia",
    },
    {
        id: 147,
        name: "Brazil",
        cca2: "BR",
        region: "South America",
    },
    {
        id: 148,
        name: "Syria",
        cca2: "SY",
        region: "Western Asia",
    },
    {
        id: 149,
        name: "Saint Helena, Ascension and Tristan da Cunha",
        cca2: "SH",
        region: "Western Africa",
    },
    {
        id: 150,
        name: "Tanzania",
        cca2: "TZ",
        region: "Eastern Africa",
    },
    {
        id: 151,
        name: "Andorra",
        cca2: "AD",
        region: "Southern Europe",
    },
    {
        id: 152,
        name: "Iran",
        cca2: "IR",
        region: "Southern Asia",
    },
    {
        id: 153,
        name: "Togo",
        cca2: "TG",
        region: "Western Africa",
    },
    {
        id: 154,
        name: "Malta",
        cca2: "MT",
        region: "Southern Europe",
    },
    {
        id: 155,
        name: "South Korea",
        cca2: "KR",
        region: "Eastern Asia",
    },
    {
        id: 156,
        name: "Samoa",
        cca2: "WS",
        region: "Polynesia",
    },
    {
        id: 157,
        name: "Germany",
        cca2: "DE",
        region: "Western Europe",
    },
    {
        id: 158,
        name: "Niger",
        cca2: "NE",
        region: "Western Africa",
    },
    {
        id: 159,
        name: "Saint Vincent and the Grenadines",
        cca2: "VC",
        region: "Caribbean",
    },
    {
        id: 160,
        name: "Jamaica",
        cca2: "JM",
        region: "Caribbean",
    },
    {
        id: 161,
        name: "Nicaragua",
        cca2: "NI",
        region: "Central America",
    },
    {
        id: 162,
        name: "Guinea",
        cca2: "GN",
        region: "Western Africa",
    },
    {
        id: 163,
        name: "Anguilla",
        cca2: "AI",
        region: "Caribbean",
    },
    {
        id: 164,
        name: "Åland Islands",
        cca2: "AX",
        region: "Northern Europe",
    },
    {
        id: 165,
        name: "Belgium",
        cca2: "BE",
        region: "Western Europe",
    },
    {
        id: 166,
        name: "Portugal",
        cca2: "PT",
        region: "Southern Europe",
    },
    {
        id: 167,
        name: "Denmark",
        cca2: "DK",
        region: "Northern Europe",
    },
    {
        id: 168,
        name: "Hong Kong",
        cca2: "HK",
        region: "Eastern Asia",
    },
    {
        id: 169,
        name: "Wallis and Futuna",
        cca2: "WF",
        region: "Polynesia",
    },
    {
        id: 170,
        name: "Austria",
        cca2: "AT",
        region: "Central Europe",
    },
    {
        id: 171,
        name: "Guinea-Bissau",
        cca2: "GW",
        region: "Western Africa",
    },
    {
        id: 172,
        name: "Monaco",
        cca2: "MC",
        region: "Western Europe",
    },
    {
        id: 173,
        name: "Namibia",
        cca2: "NA",
        region: "Southern Africa",
    },
    {
        id: 174,
        name: "United States Minor Outlying Islands",
        cca2: "UM",
        region: "North America",
    },
    {
        id: 175,
        name: "Costa Rica",
        cca2: "CR",
        region: "Central America",
    },
    {
        id: 176,
        name: "Bosnia and Herzegovina",
        cca2: "BA",
        region: "Southeast Europe",
    },
    {
        id: 177,
        name: "Macau",
        cca2: "MO",
        region: "Eastern Asia",
    },
    {
        id: 178,
        name: "Mozambique",
        cca2: "MZ",
        region: "Eastern Africa",
    },
    {
        id: 179,
        name: "Réunion",
        cca2: "RE",
        region: "Eastern Africa",
    },
    {
        id: 180,
        name: "Montenegro",
        cca2: "ME",
        region: "Southeast Europe",
    },
    {
        id: 181,
        name: "North Korea",
        cca2: "KP",
        region: "Eastern Asia",
    },
    {
        id: 182,
        name: "Northern Mariana Islands",
        cca2: "MP",
        region: "Micronesia",
    },
    {
        id: 183,
        name: "Ukraine",
        cca2: "UA",
        region: "Eastern Europe",
    },
    {
        id: 184,
        name: "Iraq",
        cca2: "IQ",
        region: "Western Asia",
    },
    {
        id: 185,
        name: "Honduras",
        cca2: "HN",
        region: "Central America",
    },
    {
        id: 186,
        name: "Angola",
        cca2: "AO",
        region: "Middle Africa",
    },
    {
        id: 187,
        name: "Sierra Leone",
        cca2: "SL",
        region: "Western Africa",
    },
    {
        id: 188,
        name: "Micronesia",
        cca2: "FM",
        region: "Micronesia",
    },
    {
        id: 189,
        name: "Cuba",
        cca2: "CU",
        region: "Caribbean",
    },
    {
        id: 190,
        name: "Turks and Caicos Islands",
        cca2: "TC",
        region: "Caribbean",
    },
    {
        id: 191,
        name: "Serbia",
        cca2: "RS",
        region: "Southeast Europe",
    },
    {
        id: 192,
        name: "Ecuador",
        cca2: "EC",
        region: "South America",
    },
    {
        id: 193,
        name: "Faroe Islands",
        cca2: "FO",
        region: "Northern Europe",
    },
    {
        id: 194,
        name: "South Sudan",
        cca2: "SS",
        region: "Middle Africa",
    },
    {
        id: 195,
        name: "Palestine",
        cca2: "PS",
        region: "Western Asia",
    },
    {
        id: 196,
        name: "Turkey",
        cca2: "TR",
        region: "Western Asia",
    },
    {
        id: 197,
        name: "Kiribati",
        cca2: "KI",
        region: "Micronesia",
    },
    {
        id: 198,
        name: "Kazakhstan",
        cca2: "KZ",
        region: "Central Asia",
    },
    {
        id: 199,
        name: "Gibraltar",
        cca2: "GI",
        region: "Southern Europe",
    },
    {
        id: 200,
        name: "Iceland",
        cca2: "IS",
        region: "Northern Europe",
    },
    {
        id: 201,
        name: "Palau",
        cca2: "PW",
        region: "Micronesia",
    },
    {
        id: 202,
        name: "Qatar",
        cca2: "QA",
        region: "Western Asia",
    },
    {
        id: 203,
        name: "Switzerland",
        cca2: "CH",
        region: "Western Europe",
    },
    {
        id: 204,
        name: "French Polynesia",
        cca2: "PF",
        region: "Polynesia",
    },
    {
        id: 205,
        name: "Pitcairn Islands",
        cca2: "PN",
        region: "Polynesia",
    },
    {
        id: 206,
        name: "Jordan",
        cca2: "JO",
        region: "Western Asia",
    },
    {
        id: 207,
        name: "Myanmar",
        cca2: "MM",
        region: "South-Eastern Asia",
    },
    {
        id: 208,
        name: "Thailand",
        cca2: "TH",
        region: "South-Eastern Asia",
    },
    {
        id: 209,
        name: "Caribbean Netherlands",
        cca2: "BQ",
        region: "Caribbean",
    },
    {
        id: 210,
        name: "Aruba",
        cca2: "AW",
        region: "Caribbean",
    },
    {
        id: 211,
        name: "Guadeloupe",
        cca2: "GP",
        region: "Caribbean",
    },
    {
        id: 212,
        name: "Nigeria",
        cca2: "NG",
        region: "Western Africa",
    },
    {
        id: 213,
        name: "Bahrain",
        cca2: "BH",
        region: "Western Asia",
    },
    {
        id: 214,
        name: "Laos",
        cca2: "LA",
        region: "South-Eastern Asia",
    },
    {
        id: 215,
        name: "Cocos (Keeling) Islands",
        cca2: "CC",
        region: "Australia and New Zealand",
    },
    {
        id: 216,
        name: "Djibouti",
        cca2: "DJ",
        region: "Eastern Africa",
    },
    {
        id: 217,
        name: "Solomon Islands",
        cca2: "SB",
        region: "Melanesia",
    },
    {
        id: 218,
        name: "Tunisia",
        cca2: "TN",
        region: "Northern Africa",
    },
    {
        id: 219,
        name: "India",
        cca2: "IN",
        region: "Southern Asia",
    },
    {
        id: 220,
        name: "San Marino",
        cca2: "SM",
        region: "Southern Europe",
    },
    {
        id: 221,
        name: "Luxembourg",
        cca2: "LU",
        region: "Western Europe",
    },
    {
        id: 222,
        name: "Sint Maarten",
        cca2: "SX",
        region: "Caribbean",
    },
    {
        id: 223,
        name: "Falkland Islands",
        cca2: "FK",
        region: "South America",
    },
    {
        id: 224,
        name: "Central African Republic",
        cca2: "CF",
        region: "Middle Africa",
    },
    {
        id: 225,
        name: "Botswana",
        cca2: "BW",
        region: "Southern Africa",
    },
    {
        id: 226,
        name: "Curaçao",
        cca2: "CW",
        region: "Caribbean",
    },
    {
        id: 227,
        name: "Guernsey",
        cca2: "GG",
        region: "Northern Europe",
    },
    {
        id: 228,
        name: "Norway",
        cca2: "NO",
        region: "Northern Europe",
    },
    {
        id: 229,
        name: "Gabon",
        cca2: "GA",
        region: "Middle Africa",
    },
    {
        id: 230,
        name: "Zimbabwe",
        cca2: "ZW",
        region: "Southern Africa",
    },
    {
        id: 231,
        name: "Lesotho",
        cca2: "LS",
        region: "Southern Africa",
    },
    {
        id: 232,
        name: "Slovenia",
        cca2: "SI",
        region: "Central Europe",
    },
    {
        id: 233,
        name: "Argentina",
        cca2: "AR",
        region: "South America",
    },
    {
        id: 234,
        name: "Burkina Faso",
        cca2: "BF",
        region: "Western Africa",
    },
    {
        id: 235,
        name: "Yemen",
        cca2: "YE",
        region: "Western Asia",
    },
    {
        id: 236,
        name: "DR Congo",
        cca2: "CD",
        region: "Middle Africa",
    },
    {
        id: 237,
        name: "Oman",
        cca2: "OM",
        region: "Western Asia",
    },
    {
        id: 238,
        name: "Indonesia",
        cca2: "ID",
        region: "South-Eastern Asia",
    },
    {
        id: 239,
        name: "Nauru",
        cca2: "NR",
        region: "Micronesia",
    },
    {
        id: 240,
        name: "Rwanda",
        cca2: "RW",
        region: "Eastern Africa",
    },
    {
        id: 241,
        name: "North Macedonia",
        cca2: "MK",
        region: "Southeast Europe",
    },
    {
        id: 242,
        name: "Kosovo",
        cca2: "XK",
        region: "Southeast Europe",
    },
    {
        id: 243,
        name: "Netherlands",
        cca2: "NL",
        region: "Western Europe",
    },
    {
        id: 244,
        name: "Unidentified",
        cca2: "NONE",
        region: "Unidentified",
    },
];

// Send to workforceForm.jsx for job titles table
export const JobTitles = [
    {
        id: 0,
        name: "Tour Guide",
    },
    {
        id: 1,
        name: "Travel Agent",
    },
    {
        id: 2,
        name: "Hotel Manager",
    },
    {
        id: 3,
        name: "Flight Attendant",
    },
    {
        id: 4,
        name: "Cruise Director",
    },
    {
        id: 5,
        name: "Event Coordinator",
    },
    {
        id: 6,
        name: "Travel Blogger/Influencer",
    },
    {
        id: 7,
        name: "Tourism Marketing Specialist",
    },
    {
        id: 8,
        name: "Resort Activities Coordinator",
    },
    {
        id: 9,
        name: "Adventure Tour Operator",
    },
];

export const JobSkills = [
    {
        id: 0,
        name: "Customer Service",
    },
    {
        id: 1,
        name: "Communication",
    },
    {
        id: 2,
        name: "Cultural Awareness",
    },
    {
        id: 3,
        name: "Problem-Solving",
    },
    {
        id: 4,
        name: "Sales and Marketing",
    },
    {
        id: 5,
        name: "Language Proficiency",
    },
    {
        id: 6,
        name: "Destination Knowledge",
    },
    {
        id: 7,
        name: "Time Management",
    },
    {
        id: 8,
        name: "Adaptability",
    },
    {
        id: 9,
        name: "Teamwork",
    },
    {
        id: 10,
        name: "Others",
    },
];
